import React, { useState, ReactNode, useEffect } from "react";
import { motion, AnimatePresence } from "motion/react";
import { Book, Search, ChevronRight, Cpu, Target, Zap, Shield, Globe, HelpCircle, FileText, ArrowRight, ExternalLink, Play, Menu, X } from "lucide-react";
import { cn } from "../lib/utils";
import { useAuth } from "../contexts/AuthContext";

export const sections = [
  {
    id: "getting-started",
    title: "Sovereign Onboarding",
    icon: <Globe className="w-5 h-5 text-accent-blue" />,
    articles: [
      { id: "intro", title: "Introduction to Freedom Wheels™", content: "Freedom Wheels™ is a decentralized, autonomous income infrastructure designed for the modern sovereign entrepreneur. Our ecosystem allows you to build, deploy, and scale automated revenue engines that operate 24/7. By leveraging neural automation and high-integrity lead intelligence, you bypass the traditional dependencies of centralized labor." },
      { id: "first-engine", title: "Your First Deployment", content: "To begin, navigate to the Engine Builder. Use our drag-and-drop interface to connect inputs (Traffic, Data) to processes (Automation, AI) and outputs (Revenue, Leads). A basic content-loop engine can be operational in under 3 minutes, generating its first synthetic yield shortly after synchronization." },
      { id: "core-sync", title: "Synchronizing the Core", content: "Once your engine is built, deploy it to the Sovereign Core. This activates the neural automation pipelines and begins the real-time revenue synthesis process. You can monitor the 'Pulse' of your system directly from the Command Center." }
    ]
  },
  {
    id: "engine-builder",
    title: "Neural Engine Architecture",
    icon: <Cpu className="w-5 h-5 text-accent-gold" />,
    articles: [
      { id: "node-types", title: "Understanding Node Types", content: "Inputs: Data sources, high-frequency organic traffic loops, and external API hooks. Processes: Neural AI agents, decision logic gates, and content synthesis modules. Outputs: Revenue settlement nodes and high-intent lead capture units." },
      { id: "flow-optimization", title: "Optimizing Flow Efficiency", content: "Minimize node latency by ensuring direct connections. Use the 'Analysis' tool to identify potential bottlenecks in your revenue pipelines. High-performance engines often utilize 'Parallel Processing' nodes to double capture-rate in high-volume traffic corridors." },
      { id: "yield-mechanics", title: "Yield Generation Mechanics", content: "Engines generate yield through micro-conversions, affiliate arbitrage, and lead-monetization loops. Each 'ping' in your dashboard represents a successful neural transaction executed by your autonomous agents." }
    ]
  },
  {
    id: "lead-intel",
    title: "Lead Intelligence Protocol",
    icon: <Target className="w-5 h-5 text-accent-blue" />,
    articles: [
      { id: "neuro-scoring", title: "Neuro-Scoring Algorithm", content: "Our AI evaluates every lead fingerprint in real-time, assigned a score from 0-100% based on intent integrity and conversion probability. Leads above 85% are automatically fast-tracked to priority high-ticket delivery nodes." },
      { id: "traffic-synthesis", title: "Organic Traffic Synthesis", content: "Freedom Wheels™ doesn't just track traffic; it creates sustainable loops. By deploying 'Traffic Magnets' in high-relevance digital sectors, your engines draw in consistent, non-paid attention that converts into actionable lead data." },
      { id: "data-vault", title: "Secure Export & Sync", content: "Your lead data is encrypted and stored in your private vault. Export datasets for external CRM synchronization at any time. All PII data is protected by Sovereign-standard encryption protocols." }
    ]
  },
  {
    id: "revenue-wallet",
    title: "Financial Infrastructure",
    icon: <Zap className="w-5 h-5 text-accent-gold" />,
    articles: [
      { id: "settlement", title: "Automated Settlement", content: "Revenue generated by your engines is settled daily into your Sovereign Wallet. Supported assets include Fiat (via Wise/Stripe) and digital assets (BTC, ETH, USDT). Our 'Zero-Latency Settlement' ensures your yield is liquid the moment it hits your account." },
      { id: "withdrawals", title: "Global Payout Relay", content: "Withdraw your earnings to any global bank account or crypto wallet via our secure multi-currency settlement gateway. We support direct bank transfers to 160+ countries and instant crypto withdrawals." },
      { id: "recursion", title: "Compound Growth Recursion", content: "By reinvesting a portion of your yield back into 'Traffic Amplifiers', you create a recursive growth loop that scales your infrastructure geometrically without requiring additional capital input." }
    ]
  }
];

export default function KnowledgeBase() {
  const [selectedArticle, setSelectedArticle] = useState(sections[0].articles[0]);
  const [searchQuery, setSearchQuery] = useState("");
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const [activeVideo, setActiveVideo] = useState<{ id: string; title: string; desc?: string; duration?: string; thumbnail?: string } | null>(null);
  const contentAreaRef = React.useRef<HTMLDivElement>(null);
  const { user } = useAuth();

  // Get Master Instructor info
  const masterInstructor = {
    name: 'MAPHALLE MALATJI',
    role: 'Master Instructor',
    photoURL: user?.photoURL || 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=2187&auto=format&fit=crop',
    quote: 'True wealth is built through autonomous systems designed with precision and scaled with intelligence.',
    isMaster: user?.email === 'malatjimaphalle1@gmail.com'
  };

  const filteredSections = sections.map(section => ({
    ...section,
    articles: section.articles.filter(a => 
      a.title.toLowerCase().includes(searchQuery.toLowerCase()) || 
      a.content.toLowerCase().includes(searchQuery.toLowerCase())
    )
  })).filter(section => section.articles.length > 0);

  const scrollToTop = () => {
    if (contentAreaRef.current) {
      contentAreaRef.current.scrollTo({ top: 0, behavior: 'smooth' });
    }
  };

  const handleWatchTutorial = (title: string, desc?: string, duration?: string, thumbnail?: string) => {
    setActiveVideo({ id: "tutorial_" + Math.random().toString(36).substr(2, 9), title, desc, duration, thumbnail });
  };

  return (
    <div className="h-full overflow-y-auto custom-scrollbar bg-bg p-8">
       <main className="max-w-7xl mx-auto w-full space-y-12">
          {/* Featured Tutorial Section */}
          <section className="mb-12 grid grid-cols-1 lg:grid-cols-3 gap-8">
             <div className="lg:col-span-2 relative aspect-video rounded-xl bg-surface border border-border-dim overflow-hidden group shadow-2xl">
                <img 
                  src="https://images.unsplash.com/photo-1581092160562-40aa08e78837?q=80&w=2940&auto=format&fit=crop" 
                  alt="Neural Masterclass" 
                  className="absolute inset-0 w-full h-full object-cover opacity-20 group-hover:scale-105 transition-transform duration-700"
                  referrerPolicy="no-referrer"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-bg via-bg/40 to-transparent z-10" />
                <div 
                  className="absolute inset-0 flex items-center justify-center z-20 cursor-pointer group"
                  onClick={() => handleWatchTutorial(
                    "Architecting Autonomous Income",
                    "A strategic deep dive into high-frequency neural connectivity and revenue synthesis logic gates.",
                    "45:00",
                    "https://images.unsplash.com/photo-1581092160562-40aa08e78837?q=80&w=2940&auto=format&fit=crop"
                  )}
                >
                    <div className="w-20 h-20 rounded-full bg-accent-gold/20 backdrop-blur-md border border-accent-gold/40 flex items-center justify-center group-hover:scale-110 transition-all shadow-[0_0_30px_rgba(245,158,11,0.3)]">
                        <Play className="w-8 h-8 text-accent-gold fill-accent-gold/30" />
                    </div>
                </div>
                <div className="absolute bottom-0 left-0 right-0 p-8 z-30">
                   <div className="flex items-center gap-2 text-accent-gold mb-3">
                      <Zap className="w-3.5 h-3.5 fill-accent-gold/50" />
                      <span className="text-[10px] font-black uppercase tracking-[0.4em]">Intelligence_Masterclass</span>
                   </div>
                   <h2 className="text-3xl font-black uppercase tracking-tighter mb-2 text-text-main shadow-sm">Architecting Autonomous Income</h2>
                   <p className="text-sm text-text-dim mb-6 max-w-lg leading-relaxed">A strategic deep dive into high-frequency neural connectivity and revenue synthesis logic gates within the Freedom Wheels™ ecosystem.</p>
                   <div className="flex items-center gap-6">
                      <button 
                        onClick={() => handleWatchTutorial("Architecting Autonomous Income", "Masterclass Introduction", "45:00")}
                        className="flex items-center gap-3 px-8 py-3 bg-accent-gold text-bg text-[11px] font-black uppercase tracking-widest rounded hover:shadow-[0_0_30px_rgba(245,158,11,0.5)] transition-all transform hover:-translate-y-0.5 active:translate-y-0"
                      >
                          <Play className="w-4 h-4 fill-bg" /> Launch_Playback
                      </button>
                      <div className="hidden md:flex items-center gap-4 text-text-dim text-[10px] font-mono tracking-widest uppercase">
                         <span>Instructor: {masterInstructor.name}</span>
                         <span className="w-1 h-1 rounded-full bg-border-dim" />
                         <span>45:00 Content Duration</span>
                      </div>
                   </div>
                </div>
             </div>
             
             <div className="grid grid-cols-1 gap-4">
                <TutorialCard 
                  icon={<Target className="w-5 h-5 text-accent-blue" />}
                  title="Lead Generation v4.2"
                  desc="Neural intent detection protocols."
                  onClick={() => handleWatchTutorial("Lead Generation v4.2", "Deep dive into intent tracking.", "12:15")}
                />
                <TutorialCard 
                  icon={<Shield className="w-5 h-5 text-accent-gold" />}
                  title="Secure Asset Vault"
                  desc="Multi-sig encryption workflow."
                  accent="gold"
                  onClick={() => handleWatchTutorial("Secure Asset Vault", "Implementing secure storage protocols.", "18:40")}
                />
                <TutorialCard 
                  icon={<Globe className="w-5 h-5 text-accent-blue" />}
                  title="Scaling Protocols"
                  desc="Autonomous market expansion hooks."
                  onClick={() => handleWatchTutorial("Scaling Protocols", "Advanced scaling techniques.", "24:30")}
                />
             </div>
          </section>

          <div className="grid grid-cols-1 lg:grid-cols-[320px_1fr] gap-10">
          {/* Sidebar Navigation */}
          <aside className={cn(
            "space-y-8 lg:block",
            isMenuOpen ? "fixed inset-0 top-[60px] bg-bg z-40 p-8 block overflow-y-auto" : "hidden"
          )}>
             <div className="relative mb-8">
               <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-text-dim" />
               <input 
                 type="text" 
                 value={searchQuery}
                 onChange={(e) => setSearchQuery(e.target.value)}
                 placeholder="Search Intelligence..." 
                 className="w-full bg-surface border border-border-dim rounded py-2.5 pl-10 pr-4 text-[11px] font-mono outline-none focus:border-accent-blue transition-all"
               />
             </div>

             {filteredSections.map((section) => (
               <div key={section.id} className="space-y-4">
                 <div className="flex items-center gap-3 text-[11px] font-black uppercase tracking-[0.25em] text-accent-blue/60 mb-2 px-2">
                   {section.icon}
                   {section.title}
                 </div>
                 <div className="space-y-1">
                   {section.articles.map((article) => (
                     <button
                       key={article.id}
                       onClick={() => {
                         setSelectedArticle(article);
                         scrollToTop();
                         setIsMenuOpen(false);
                       }}
                       className={cn(
                         "w-full text-left px-4 py-3 rounded text-[11px] font-bold transition-all flex items-center justify-between group relative overflow-hidden",
                         selectedArticle.id === article.id 
                           ? "bg-accent-blue/10 text-accent-blue border-l-2 border-l-accent-blue pl-6" 
                           : "text-text-dim hover:bg-surface hover:text-text-main border-l-2 border-l-transparent"
                       )}
                     >
                       <span className="relative z-10">{article.title}</span>
                       <ChevronRight className={cn("w-3.5 h-3.5 opacity-0 group-hover:opacity-100 transition-all group-hover:translate-x-1", selectedArticle.id === article.id && "opacity-100")} />
                     </button>
                   ))}
                 </div>
               </div>
             ))}
          </aside>

          {/* Content Area */}
          <section ref={contentAreaRef} className="bg-surface border border-border-dim rounded-2xl p-8 md:p-16 overflow-y-auto relative min-h-[700px] shadow-sm">
             <AnimatePresence mode="wait">
               <motion.div
                 key={selectedArticle.id}
                 initial={{ opacity: 0, x: 20 }}
                 animate={{ opacity: 1, x: 0 }}
                 exit={{ opacity: 0, x: -20 }}
                 transition={{ duration: 0.4, ease: [0.23, 1, 0.32, 1] }}
               >
                 <div className="flex items-center gap-3 text-[10px] font-black text-accent-gold uppercase tracking-[0.3em] mb-8 py-2 px-4 bg-accent-gold/5 border border-accent-gold/20 rounded inline-flex">
                    <FileText className="w-4 h-4" />
                    Protocol_Intelligence_Article
                 </div>
                 
                 <h2 className="text-4xl md:text-6xl font-black mb-10 leading-[0.9] uppercase tracking-tighter text-text-main">
                   {selectedArticle.title}
                 </h2>

                 <div className="prose prose-invert max-w-none">
                    <p className="text-lg md:text-xl text-text-dim leading-relaxed font-medium mb-12 border-l-4 border-border-dim pl-8">
                      {selectedArticle.content}
                    </p>
                    
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mt-16 pt-16 border-t border-border-dim">
                       <div className="p-8 bg-bg border border-border-dim rounded-xl hover:border-accent-blue transition-all group cursor-pointer">
                          <div className="w-12 h-12 rounded bg-accent-blue/10 flex items-center justify-center mb-6 text-accent-blue group-hover:scale-110 transition-transform">
                             <Cpu className="w-6 h-6" />
                          </div>
                          <h4 className="text-sm font-black uppercase tracking-widest text-text-main mb-3">Technical Infrastructure</h4>
                          <p className="text-xs text-text-dim leading-relaxed mb-6">Access low-level node benchmarks, latency logs, and neural synchronization graphs for this logic module.</p>
                          <div className="flex items-center gap-2 text-accent-blue font-black text-[10px] uppercase tracking-widest group-hover:gap-4 transition-all">
                            Request_Log_Access <ArrowRight className="w-4 h-4" />
                          </div>
                       </div>

                       <div className="p-8 bg-bg border border-border-dim rounded-xl hover:border-accent-gold transition-all group cursor-pointer" onClick={() => handleWatchTutorial(selectedArticle.title)}>
                          <div className="w-12 h-12 rounded bg-accent-gold/10 flex items-center justify-center mb-6 text-accent-gold group-hover:scale-110 transition-transform">
                             <Play className="w-6 h-6 fill-accent-gold/30" />
                          </div>
                          <h4 className="text-sm font-black uppercase tracking-widest text-text-main mb-3">Visual Walkthrough</h4>
                          <p className="text-xs text-text-dim leading-relaxed mb-6">Watch the Sovereign Core neural team deploy and optimize this specific protocol in a live environment.</p>
                          <div className="flex items-center gap-2 text-accent-gold font-black text-[10px] uppercase tracking-widest group-hover:gap-4 transition-all">
                            Synchronize_Playback <ExternalLink className="w-4 h-4" />
                          </div>
                       </div>
                    </div>
                 </div>
               </motion.div>
             </AnimatePresence>

             {/* Help Floating Trigger */}
             <div className="absolute bottom-12 right-12">
                <button className="flex items-center gap-3 px-6 py-3 bg-bg border border-border-dim rounded-full text-[10px] font-black uppercase tracking-widest hover:border-accent-blue hover:text-accent-blue transition-all shadow-xl group">
                  <span className="w-2 h-2 rounded-full bg-accent-blue animate-pulse" />
                  Live_Node_Support
                  <ChevronRight className="w-3.5 h-3.5 group-hover:translate-x-1 transition-transform" />
                </button>
             </div>
          </section>
        </div>
      </main>

      {/* Video Portal Modal */}
      <AnimatePresence>
        {activeVideo && (
          <motion.div 
            initial={{ opacity: 0 }} 
            animate={{ opacity: 1 }} 
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-[100] bg-bg/95 backdrop-blur-2xl flex items-center justify-center p-4 md:p-12 overflow-hidden"
          >
            <motion.div 
              initial={{ scale: 0.95, y: 20 }}
              animate={{ scale: 1, y: 0 }}
              exit={{ scale: 0.95, y: 20 }}
              className="w-full max-w-7xl aspect-[21/9] bg-surface border border-border-dim rounded-3xl overflow-hidden relative shadow-[0_0_100px_rgba(0,0,0,0.8)] grid grid-cols-1 lg:grid-cols-[1fr_380px]"
            >
              {/* Main Player Area */}
              <div className="relative group overflow-hidden bg-black flex items-center justify-center">
                {/* Simulated Video Content */}
                <div className="absolute inset-0 z-0">
                  <img 
                    src={activeVideo.thumbnail || "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=2944&auto=format&fit=crop"} 
                    className="w-full h-full object-cover opacity-40 mix-blend-screen animate-pulse"
                    alt="Neural Feed Backdrop"
                  />
                  {/* Neural Grid Overlay */}
                  <div className="absolute inset-0 opacity-20 pointer-events-none" style={{ backgroundImage: 'radial-gradient(circle, #00f2ff 1px, transparent 1px)', backgroundSize: '40px 40px' }} />
                  {/* Scanning Line */}
                  <motion.div 
                    animate={{ top: ['0%', '100%'] }}
                    transition={{ duration: 4, repeat: Infinity, ease: "linear" }}
                    className="absolute inset-x-0 h-[2px] bg-gradient-to-r from-transparent via-accent-blue to-transparent z-10 opacity-50"
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-bg via-transparent to-bg/40" />
                </div>

                <div className="relative z-10 text-center space-y-8 max-w-2xl px-8">
                  <motion.div 
                    initial={{ scale: 0.8, opacity: 0 }}
                    animate={{ scale: 1, opacity: 1 }}
                    transition={{ delay: 0.3 }}
                    className="w-32 h-32 rounded-full bg-accent-blue/10 border-2 border-accent-blue/30 flex items-center justify-center mx-auto relative group/icon"
                  >
                     <div className="absolute inset-0 rounded-full border border-accent-blue animate-ping opacity-20" />
                     <div className="absolute inset-[-10px] rounded-full border border-dashed border-accent-blue/20 animate-spin-slow" />
                     <Cpu className="w-12 h-12 text-accent-blue group-hover/icon:scale-110 transition-transform" />
                  </motion.div>
                  
                  <div className="space-y-4">
                    <motion.div
                      initial={{ opacity: 0, y: 10 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ delay: 0.5 }}
                    >
                      <h4 className="text-2xl font-black uppercase tracking-tighter text-text-main mb-2">Establishing Neural Synchronization</h4>
                      <div className="flex items-center justify-center gap-4">
                        <p className="text-[10px] font-mono text-accent-blue tracking-[0.3em] uppercase">Status: STREAMING_INTEL_NODES</p>
                        <div className="flex gap-1">
                           {[1,2,3].map(i => (
                             <motion.div 
                               key={i}
                               animate={{ height: [4, 12, 4] }}
                               transition={{ duration: 1, repeat: Infinity, delay: i * 0.2 }}
                               className="w-1 bg-accent-blue"
                             />
                           ))}
                        </div>
                      </div>
                    </motion.div>

                    <div className="w-64 h-1 bg-border-dim rounded-full mx-auto overflow-hidden relative">
                       <motion.div 
                         initial={{ width: 0 }}
                         animate={{ width: "100%" }}
                         transition={{ duration: 10, repeat: Infinity }}
                         className="h-full bg-accent-blue shadow-[0_0_15px_#00f2ff]"
                       />
                    </div>
                  </div>
                </div>

                {/* Player Controls overlay */}
                <div className="absolute inset-x-0 bottom-0 p-10 flex flex-col gap-6 z-20 bg-gradient-to-t from-bg to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500">
                   <div className="w-full h-1 bg-white/10 rounded-full cursor-pointer relative group/progress">
                      <div className="absolute inset-0 bg-accent-blue w-1/3 rounded-full shadow-[0_0_10px_#00f2ff]" />
                      <div className="absolute left-[33%] top-1/2 -translate-y-1/2 w-4 h-4 rounded-full bg-white shadow-xl scale-0 group-hover/progress:scale-100 transition-transform" />
                   </div>
                   <div className="flex items-center justify-between">
                      <div className="flex items-center gap-8">
                         <button className="text-text-main hover:text-accent-blue transition-colors"><Play className="w-8 h-8 fill-current" /></button>
                         <div className="flex flex-col">
                            <span className="text-[10px] font-mono text-text-dim">TIMELINE_REMAINING</span>
                            <span className="text-xs font-black font-mono text-text-main">12:42 / {activeVideo.duration || "45:00"}</span>
                         </div>
                      </div>
                      <div className="flex items-center gap-6">
                         <div className="flex items-center gap-2 px-3 py-1 bg-white/5 rounded border border-white/10">
                            <Zap className="w-3 h-3 text-accent-gold" />
                            <span className="text-[10px] font-black uppercase text-accent-gold tracking-widest">Neural_4K</span>
                         </div>
                         <Shield className="w-5 h-5 text-text-dim hover:text-text-main transition-colors cursor-pointer" />
                         <Menu className="w-5 h-5 text-text-dim hover:text-text-main transition-colors cursor-pointer" />
                      </div>
                   </div>
                </div>
              </div>

              {/* Sidebar Info Area */}
              <div className="bg-surface/50 border-l border-border-dim p-10 flex flex-col">
                 <div className="flex items-center justify-between mb-10">
                    <div className="px-3 py-1 rounded bg-accent-blue/10 border border-accent-blue/30 text-accent-blue text-[8px] font-black uppercase tracking-widest">
                       Module_Protocol
                    </div>
                    <button 
                      onClick={() => setActiveVideo(null)}
                      className="p-2 hover:bg-bg rounded-lg text-text-dim hover:text-text-main transition-colors"
                    >
                      <X className="w-5 h-5" />
                    </button>
                 </div>

                 <div className="flex-1 space-y-10">
                    <div>
                       <h3 className="text-2xl font-black uppercase tracking-tighter text-text-main mb-4 leading-tight">{activeVideo.title}</h3>
                       <p className="text-xs text-text-dim leading-relaxed font-mono uppercase opacity-70">
                         {activeVideo.desc || "Comprehensive infrastructure briefing for sovereign neural deployments."}
                       </p>
                    </div>

                    <div className="p-6 bg-bg border border-border-dim rounded-2xl space-y-6">
                       <div className="flex items-center gap-4">
                          <div className="w-12 h-12 rounded-xl bg-accent-gold border border-accent-gold/50 flex items-center justify-center text-bg shadow-lg overflow-hidden">
                             <img 
                               src={masterInstructor.photoURL}
                               className="w-full h-full object-cover rounded-xl"
                               alt={masterInstructor.name}
                             />
                          </div>
                          <div>
                             <div className="text-[9px] font-black uppercase text-accent-gold tracking-widest mb-0.5 flex items-center gap-2">
                               {masterInstructor.isMaster && <span>🎓</span>}
                               {masterInstructor.role}
                             </div>
                             <div className="text-sm font-black uppercase text-text-main">{masterInstructor.name}</div>
                          </div>
                       </div>
                       <p className="text-[10px] text-text-dim leading-relaxed italic">"{masterInstructor.quote}"</p>
                    </div>

                    <div className="space-y-4">
                       <h5 className="text-[9px] font-black uppercase text-text-dim tracking-[0.2em]">Deployment_Schedule</h5>
                       <div className="space-y-2">
                          {[
                            { time: "00:00", title: "Core Logic Sync" },
                            { time: "12:15", title: "Neural Mesh Setup" },
                            { time: "24:30", title: "Yield Optimization" },
                            { time: "38:00", title: "QA & Verification" }
                          ].map((step, idx) => (
                            <div key={idx} className="flex items-center justify-between p-3 rounded-lg bg-bg/40 border border-border-dim/50 hover:border-accent-blue/40 transition-all cursor-pointer group">
                               <div className="flex items-center gap-3">
                                  <span className="text-[9px] font-mono text-accent-blue">{step.time}</span>
                                  <span className="text-[10px] font-black uppercase text-text-dim group-hover:text-text-main transition-colors">{step.title}</span>
                               </div>
                               <ChevronRight className="w-3 h-3 text-text-dim group-hover:translate-x-1 transition-transform" />
                            </div>
                          ))}
                       </div>
                    </div>
                 </div>

                 <div className="pt-8 border-t border-border-dim flex items-center justify-between">
                    <div className="flex -space-x-2">
                       {[1,2,3,4].map(i => (
                         <div key={i} className="w-8 h-8 rounded-full border-2 border-surface bg-border-dim" />
                       ))}
                       <div className="w-8 h-8 rounded-full border-2 border-surface bg-bg flex items-center justify-center text-[8px] font-black text-text-dim">+2.4k</div>
                    </div>
                    <span className="text-[9px] font-black text-accent-blue uppercase tracking-widest animate-pulse">Syncing_Nodes...</span>
                 </div>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

function TutorialCard({ icon, title, desc, onClick, accent = "blue" }: { icon: React.ReactNode, title: string, desc: string, onClick: () => void, accent?: "blue" | "gold" }) {
  return (
    <div 
      onClick={onClick}
      className={cn(
        "p-6 rounded-xl bg-surface border border-border-dim transition-all group cursor-pointer hover:-translate-y-1 shadow-lg",
        accent === "blue" ? "hover:border-accent-blue" : "hover:border-accent-gold"
      )}
    >
       <div className="flex items-center justify-between mb-4">
          <h3 className="text-[11px] font-black uppercase tracking-widest flex items-center gap-3">
             <div className={cn("p-2 rounded bg-bg border border-border-dim", accent === "blue" ? "text-accent-blue" : "text-accent-gold")}>{icon}</div>
             <span className="group-hover:text-text-main transition-colors">{title}</span>
          </h3>
          <ArrowRight className={cn("w-4 h-4 text-text-dim transition-all group-hover:translate-x-1", accent === "blue" ? "group-hover:text-accent-blue" : "group-hover:text-accent-gold")} />
       </div>
       <p className="text-[11px] text-text-dim leading-relaxed">{desc}</p>
    </div>
  );
}
